package selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddNewOwnersTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addNewOwners() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1062, 846));
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) span:nth-child(2)")).click();
    driver.findElement(By.linkText("Add Owner")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("Julian");
    driver.findElement(By.id("lastName")).sendKeys("Martin");
    driver.findElement(By.id("address")).sendKeys("Madrid");
    driver.findElement(By.id("city")).sendKeys("Madrid");
    driver.findElement(By.id("telephone")).sendKeys("000000000");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".active")).click();
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("Martin");
    driver.findElement(By.id("lastName")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".active")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.linkText("3")).click();
    driver.findElement(By.linkText("2")).click();
  }
}
